# Generated by Django 6.0.3 on 2026-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_achievement_owner_achievementcat_cat_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('White', 'White'), ('Ginger', 'Ginger'), ('Mixed', 'Mixed')], max_length=16),
        ),
    ]
